la_liga:
  league_id: 140
  scope: "domestic"
  region: "Europe"

champions_league:
  league_id: 2
  scope: "continental"
  region: "Europe"

brasileirao:
  league_id: 71
  scope: "domestic"
  region: "South America"

libertadores:
  league_id: 13
  scope: "continental"
  region: "South America"

copa_do_brasil:
  league_id: 73
  scope: "domestic"
  region: "South America"

copa_del_rey:
  league_id: 143
  scope: "domestic"
  region: "Europe"

world_cup:
  league_id: 1
  scope: "international"
  region: "Global"